name: Build & Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up projects and install dependencies
        run: pnpm install
      - name: Build projects
        run: pnpm run build
      - name: Automated tests
        run: pnpm run test
